/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lzwu' at '12/27/17 3:14 PM' with Gradle 3.0
 *
 * @author lzwu, @date 12/27/17 3:14 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
